# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'agregar_producto.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from menu_principal import Ui_Main_Menu


class Ui_Add_Product(object):
    def setupUi(self, Add_Product):
        Add_Product.setObjectName("Add_Product")
        Add_Product.resize(645, 694)
        Add_Product.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Add_Product.setStatusTip("")
        Add_Product.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(Add_Product)
        self.centralwidget.setStyleSheet("QWidget{\n"
                                         "    background-color: rgb(236, 236, 236)\n"
                                         "}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setStyleSheet("QPushButton{\n"
                                 "    padding: 20;\n"
                                 "    border:2px solid black;\n"
                                 "    border-radius: 6px;\n"
                                 "    color: rgb(39, 39, 39)\n"
                                 "}\n"
                                 "\n"
                                 "#Antibiotics{\n"
                                 "    background-color: rgb(255, 0, 0);\n"
                                 "}\n"
                                 "\n"
                                 "#Antibiotics::hover{\n"
                                 "    background-color: rgb(252, 104, 104);\n"
                                 "    border:2px solid rgb(170, 0, 0);\n"
                                 "}\n"
                                 "\n"
                                 "#Antibiotics::pressed{\n"
                                 "    background-color: rgb(255, 206, 206);\n"
                                 "    border-color:gray;\n"
                                 "}\n"
                                 "\n"
                                 "#Fertilizers{\n"
                                 "    background-color: rgb(0, 81, 255);\n"
                                 "}\n"
                                 "\n"
                                 "#Fertilizers::hover{\n"
                                 "    background-color: rgb(72, 188, 250);\n"
                                 "    border:2px solid rgb(0, 0, 127);\n"
                                 "}\n"
                                 "\n"
                                 "#Fertilizers::pressed{\n"
                                 "    background-color: rgb(202, 246, 255);\n"
                                 "    border-color:gray;\n"
                                 "}\n"
                                 "\n"
                                 "#Pest_Control{\n"
                                 "    background-color: rgb(0, 170, 0);\n"
                                 "}\n"
                                 "\n"
                                 "#Pest_Control::hover{\n"
                                 "    background-color: rgb(70, 224, 87);\n"
                                 "    border: 2px solid rgb(0, 85, 0)\n"
                                 "}\n"
                                 "\n"
                                 "#Pest_Control::pressed{\n"
                                 "    background-color: rgb(208, 255, 208);\n"
                                 "    border-color:gray;\n"
                                 "}\n"
                                 "\n"
                                 "#Back_Button{\n"
                                 "    background-color: rgb(255, 208, 20)\n"
                                 "}\n"
                                 "\n"
                                 "#Back_Button::hover{\n"
                                 "    background-color: rgb(252, 225, 104);\n"
                                 "    border-color: rgb(138, 113, 0);\n"
                                 "}\n"
                                 "\n"
                                 "#Back_Button::pressed{\n"
                                 "    background-color: rgb(252, 241, 189);\n"
                                 "    border-color:gray;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton::hover{\n"
                                 "    background-color: rgb(85, 170, 255);\n"
                                 "    color: white;\n"
                                 "    border-width: 2px;\n"
                                 "    border-color: rgb(0, 4, 255);\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton::pressed{\n"
                                 "    color: grey;\n"
                                 "}\n"
                                 "\n"
                                 "QFrame{\n"
                                 "    padding: 50;\n"
                                 "}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Introduction = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Introduction.setFont(font)
        self.Introduction.setObjectName("Introduction")
        self.verticalLayout.addWidget(self.Introduction)
        self.Antibiotics = QtWidgets.QPushButton(self.frame)
        self.Antibiotics.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Antibiotics.sizePolicy().hasHeightForWidth())
        self.Antibiotics.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Antibiotics.setFont(font)
        self.Antibiotics.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Antibiotics.setToolTip("")
        self.Antibiotics.setStatusTip("")
        self.Antibiotics.setWhatsThis("")
        self.Antibiotics.setStyleSheet("")
        self.Antibiotics.setObjectName("Antibiotics")
        self.verticalLayout.addWidget(self.Antibiotics)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.Fertilizers = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Fertilizers.setFont(font)
        self.Fertilizers.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Fertilizers.setToolTip("")
        self.Fertilizers.setObjectName("Fertilizers")
        self.verticalLayout.addWidget(self.Fertilizers)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.Pest_Control = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Pest_Control.sizePolicy().hasHeightForWidth())
        self.Pest_Control.setSizePolicy(sizePolicy)
        self.Pest_Control.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Pest_Control.setFont(font)
        self.Pest_Control.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Pest_Control.setMouseTracking(False)
        self.Pest_Control.setTabletTracking(False)
        self.Pest_Control.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Pest_Control.setToolTip("")
        self.Pest_Control.setStyleSheet("")
        self.Pest_Control.setAutoRepeat(False)
        self.Pest_Control.setAutoDefault(False)
        self.Pest_Control.setDefault(False)
        self.Pest_Control.setFlat(False)
        self.Pest_Control.setObjectName("Pest_Control")
        self.verticalLayout.addWidget(self.Pest_Control)
        self.Back_Button = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Back_Button.setFont(font)
        self.Back_Button.setObjectName("Back_Button")
        self.verticalLayout.addWidget(self.Back_Button)
        self.verticalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        Add_Product.setCentralWidget(self.centralwidget)

        self.retranslateUi(Add_Product)
        QtCore.QMetaObject.connectSlotsByName(Add_Product)

    def retranslateUi(self, Add_Product):
        _translate = QtCore.QCoreApplication.translate
        Add_Product.setWindowTitle(_translate("Add_Product", "Administrador de Vivero"))
        self.Introduction.setText(_translate("Add_Product",
                                             "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">Indique el tipo de producto que </span></p><p align=\"center\"><span style=\" font-size:22pt;\">desea agregar al sistema</span></p></body></html>"))
        self.Antibiotics.setText(_translate("Add_Product", "ANTIBIÓTICO"))
        self.Fertilizers.setText(_translate("Add_Product", "FERTILIZANTE"))
        self.Pest_Control.setText(_translate("Add_Product", "CONTROL DE PLAGAS"))
        self.Back_Button.setText(_translate("Add_Product", "RETROCEDER"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Add_Product = QtWidgets.QMainWindow()
    ui = Ui_Add_Product()
    ui.setupUi(Add_Product)
    Add_Product.show()
    sys.exit(app.exec_())
