# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'agregar_cliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
from Controller.client_controler import ClientControler 
from comprar_producto import Ui_Purchase_Product
from utils import show_pop_up, validate_items, show_message


class Ui_Add_Client(object):
    def __init__(self):
        self.ui = None
        self.ventana = None

    def back_main_menu_window(self, Add_Client, main_menu_window):
        main_menu_window.show()
        Add_Client.close()


    def setupUi(self, Add_Client, Main_Menu):
        Add_Client.setObjectName("Add_Client")
        Add_Client.resize(799, 600)
        self.Background = QtWidgets.QWidget(Add_Client)
        self.Background.setStyleSheet("QWidget{\n"
                                      "    background-color: rgb(236, 236, 236)\n"
                                      "}")
        self.Background.setObjectName("Background")
        self.frame = QtWidgets.QFrame(self.Background)
        self.frame.setGeometry(QtCore.QRect(193, 0, 412, 600))
        self.frame.setStyleSheet("QLineEdit{\n"
                                 "    background-color: white;\n"
                                 "    font-size: 20px;\n"
                                 "}\n"
                                 "\n"
                                 "QLabel{\n"
                                 "    font-size: 20px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton{\n"
                                 "    font-size: 20px;\n"
                                 "    border: 2px solid;\n"
                                 "    border-radius: 6px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton::pressed{\n"
                                 "    color: rgb(225, 225, 225);\n"
                                 "    border-radius: 0;\n"
                                 "}\n"
                                 "\n"
                                 "#Confirm{\n"
                                 "    background-color: rgb(87, 255, 75);\n"
                                 "    border-color: rgb(0, 172, 0);\n"
                                 "}\n"
                                 "\n"
                                 "#Confirm::hover{\n"
                                 "    background-color: rgb(56, 247, 42);\n"
                                 "}\n"
                                 "\n"
                                 "#Confirm::pressed{\n"
                                 "    background-color: rgb(0, 172, 0);\n"
                                 "    border-color: rgb(87, 255, 75)\n"
                                 "}\n"
                                 "\n"
                                 "#Cancel{\n"
                                 "    background-color: rgb(242, 90, 90);\n"
                                 "    border-color: rgb(255, 0, 0)\n"
                                 "}\n"
                                 "\n"
                                 "#Cancel::hover{\n"
                                 "    background-color: rgb(237, 50, 50);\n"
                                 "    border-color: rgb(255, 0, 0)\n"
                                 "}\n"
                                 "\n"
                                 "#Cancel::pressed{\n"
                                 "    background-color: rgb(255, 0, 0);\n"
                                 "    border-color: rgb(255, 101, 101)\n"
                                 "}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.identification = QtWidgets.QFrame(self.frame)
        self.identification.setGeometry(QtCore.QRect(10, 150, 391, 61))
        self.identification.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.identification.setFrameShadow(QtWidgets.QFrame.Raised)
        self.identification.setObjectName("identification")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.identification)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Label_2 = QtWidgets.QLabel(self.identification)
        self.Label_2.setStyleSheet("QLabel{\n"
                                   "    margin-right: 25px;\n"
                                   "}")
        self.Label_2.setObjectName("Label_2")
        self.horizontalLayout_2.addWidget(self.Label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.identification)
        self.lineEdit.setAcceptDrops(False)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.Name = QtWidgets.QFrame(self.frame)
        self.Name.setGeometry(QtCore.QRect(10, 240, 391, 61))
        self.Name.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Name.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Name.setObjectName("Name")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Name)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Label = QtWidgets.QLabel(self.Name)
        self.Label.setStyleSheet("QLabel{\n"
                                 "    margin-right: 20px\n"
                                 "}")
        self.Label.setObjectName("Label")
        self.horizontalLayout.addWidget(self.Label)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Name)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 340, 411, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Cancel = QtWidgets.QPushButton(self.horizontalLayoutWidget, clicked=lambda: self.back_main_menu_window(Add_Client, Main_Menu))
        self.Cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Cancel.setObjectName("Cancel")
        self.horizontalLayout_3.addWidget(self.Cancel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.Confirm = QtWidgets.QPushButton(self.horizontalLayoutWidget, clicked=lambda: self.open_purchase_product_window(Add_Client, Main_Menu))
        self.Confirm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Confirm.setObjectName("Confirm")
        self.horizontalLayout_3.addWidget(self.Confirm)
        self.Instruction = QtWidgets.QLabel(self.frame)
        self.Instruction.setGeometry(QtCore.QRect(0, 40, 411, 71))
        self.Instruction.setObjectName("Instruction")
        Add_Client.setCentralWidget(self.Background)

        Main_Menu.hide()

        self.retranslateUi(Add_Client)
        QtCore.QMetaObject.connectSlotsByName(Add_Client)

    def retranslateUi(self, Add_Client):
        _translate = QtCore.QCoreApplication.translate
        Add_Client.setWindowTitle(_translate("Add_Client", "Información del Cliente"))
        self.Label_2.setText(_translate("Add_Client", "Cédula"))
        self.Label.setText(_translate("Add_Client", "Nombre"))
        self.Cancel.setText(_translate("Add_Client", "Cancelar"))
        self.Confirm.setText(_translate("Add_Client", "Confirmar"))
        self.Instruction.setText(_translate("Add_Client",
                                            "<html><head/><body><p align=\"center\"><span style=\" "
                                            "font-size:15pt;\">Ingrese la información del cliente</span></p><p "
                                            "align=\"center\"><span style=\" font-size:15pt;\">(Cédula sin puntos, "
                                            "comas ni guiones)</span></p></body></html>"))

    def open_purchase_product_window(self, Add_Client, Main_Menu):
        name = self.lineEdit_2.text().strip()
        dni = self.lineEdit.text().strip()
        if not validate_items(name, dni):
            show_pop_up("Administracion Tienda Agricola", "Error al buscar cliente. Debe completar todos los campos",
                        QtWidgets.QMessageBox.Warning)
        else:
            client = ClientControler.search(name=name, dni=dni)
            if not client:
                client = ClientControler.create(name=name, dni=dni)
                show_message("Se creó el cliente con exito")
                
            self.ventana = QtWidgets.QMainWindow()
            self.ui = Ui_Purchase_Product()
            self.ui.setupUi(self.ventana, Add_Client, Main_Menu, client)
            self.ventana.show()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Add_Client = QtWidgets.QMainWindow()
    ui = Ui_Add_Client()
    ui.setupUi(Add_Client)
    Add_Client.show()
    sys.exit(app.exec_())
