# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys 
sys.path.append(r"C:\Users\juanb\OneDrive\Documentos\GitHub\Proyecto_Final_Progra_IV")

from PyQt5 import QtCore, QtGui, QtWidgets
from agregar_cliente import Ui_Add_Client
from buscar_cliente import Ui_Search_Client
from agregar_producto import Ui_Add_Product


class Ui_Main_Menu(object):
    def __init__(self):
        self.ui = None
        self.ventana = None

    def setupUi(self, Main_Menu):
        Main_Menu.setObjectName("Main_Menu")
        Main_Menu.resize(800, 600)
        Main_Menu.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Main_Menu.setStatusTip("")
        Main_Menu.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(Main_Menu)
        self.centralwidget.setStyleSheet("QWidget{\n"
                                         "    background-color: rgb(236, 236, 236)\n"
                                         "}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setStyleSheet("QPushButton{\n"
                                 "    padding: 20;\n"
                                 "     background-color: rgb(236, 236, 236);\n"
                                 "    border: 2px solid rgb(182, 182, 182);\n"
                                 "    border-radius: 6px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton::hover{\n"
                                 "    background-color: rgb(85, 170, 255);\n"
                                 "    color: white;\n"
                                 "    border-width: 2px;\n"
                                 "    border-color: rgb(0, 4, 255);\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton::pressed{\n"
                                 "    background-color: rgb(0, 0, 127);\n"
                                 "    color: gray;\n"
                                 "}\n"
                                 "\n"
                                 "QFrame{\n"
                                 "    padding: 50;\n"
                                 "}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.buy = QtWidgets.QPushButton(self.frame)
        self.buy.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buy.sizePolicy().hasHeightForWidth())
        self.buy.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.buy.setFont(font)
        self.buy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buy.setStatusTip("")
        self.buy.setStyleSheet("")
        self.buy.setObjectName("buy")
        self.verticalLayout.addWidget(self.buy)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.search_id = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.search_id.setFont(font)
        self.search_id.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search_id.setObjectName("search_id")
        self.verticalLayout.addWidget(self.search_id)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.add_product = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_product.sizePolicy().hasHeightForWidth())
        self.add_product.setSizePolicy(sizePolicy)
        self.add_product.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.add_product.setFont(font)
        self.add_product.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_product.setMouseTracking(False)
        self.add_product.setTabletTracking(False)
        self.add_product.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.add_product.setStyleSheet("")
        self.add_product.setAutoRepeat(False)
        self.add_product.setAutoDefault(False)
        self.add_product.setDefault(False)
        self.add_product.setFlat(False)
        self.add_product.setObjectName("add_product")
        self.verticalLayout.addWidget(self.add_product)
        self.verticalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        Main_Menu.setCentralWidget(self.centralwidget)

        self.buy.clicked.connect(self.open_add_client_window)
        self.search_id.clicked.connect(self.open_search_client_window)
        self.add_product.clicked.connect(self.open_add_product_window)

        self.retranslateUi(Main_Menu)
        QtCore.QMetaObject.connectSlotsByName(Main_Menu)

    def retranslateUi(self, Main_Menu):
        _translate = QtCore.QCoreApplication.translate
        Main_Menu.setWindowTitle(_translate("Main_Menu", "Administrador de Vivero"))
        self.buy.setToolTip(_translate("Main_Menu", "<html><head/><body><p>Navega por nuestro stock</p></body></html>"))
        self.buy.setWhatsThis(_translate("Main_Menu", "<html><head/><body><p><br/></p></body></html>"))
        self.buy.setText(_translate("Main_Menu", "Comprar"))
        self.search_id.setToolTip(
            _translate("Main_Menu", "<html><head/><body><p>Busca a un cliente por su cédula</p></body></html>"))
        self.search_id.setText(_translate("Main_Menu", "Buscar Cliente"))
        self.add_product.setToolTip(
            _translate("Main_Menu", "<html><head/><body><p>Añade un producto a la base de datos</p></body></html>"))
        self.add_product.setText(_translate("Main_Menu", "Agregar Producto"))

    def open_add_client_window(self):
        self.ventana = QtWidgets.QMainWindow()
        self.ui = Ui_Add_Client()
        self.ui.setupUi(self.ventana, Main_Menu)
        self.ventana.show()

    def open_search_client_window(self):
        self.ventana = QtWidgets.QMainWindow()
        self.ui = Ui_Search_Client()
        self.ui.setupUi(self.ventana, Main_Menu)
        self.ventana.show()

    def open_add_product_window(self):
        self.ventana = QtWidgets.QMainWindow()
        self.ui = Ui_Add_Product()
        self.ui.setupUi(self.ventana)
        self.ventana.show()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Main_Menu = QtWidgets.QMainWindow()
    ui = Ui_Main_Menu()
    ui.setupUi(Main_Menu)
    Main_Menu.show()
    sys.exit(app.exec_())
