# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nuevo_antibiotico.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Controller import antibiotic_controller
from utils import validate_items, show_message, show_pop_up


class Ui_Add_Antibiotic(object):

    def back_add_product_window(self, Add_Antibiotic, Add_Product):
        Add_Product.show()
        Add_Antibiotic.close()

    def setupUi(self, Add_Antibiotic, Add_Product, Main_Menu):
        Add_Antibiotic.setObjectName("Add_Antibiotic")
        Add_Antibiotic.resize(799, 608)
        self.Background = QtWidgets.QWidget(Add_Antibiotic)
        self.Background.setStyleSheet("QWidget{\n"
                                      "    background-color: rgb(236, 236, 236)\n"
                                      "}")
        self.Background.setObjectName("Background")
        self.frame = QtWidgets.QFrame(self.Background)
        self.frame.setGeometry(QtCore.QRect(133, 0, 521, 601))
        self.frame.setStyleSheet("QLineEdit{\n"
                                 "    background-color: white;\n"
                                 "    font-size: 20px;\n"
                                 "}\n"
                                 "\n"
                                 "QLabel{\n"
                                 "    font-size: 20px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton{\n"
                                 "    font-size: 20px;\n"
                                 "    border: 2px solid;\n"
                                 "    border-radius: 6px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton::pressed{\n"
                                 "    color: rgb(225, 225, 225);\n"
                                 "    border-radius: 0;\n"
                                 "}\n"
                                 "\n"
                                 "#Add{\n"
                                 "    background-color: rgb(87, 255, 75);\n"
                                 "    border-color: rgb(0, 172, 0);\n"
                                 "}\n"
                                 "\n"
                                 "#Add::hover{\n"
                                 "    background-color: rgb(56, 247, 42);\n"
                                 "}\n"
                                 "\n"
                                 "#Add::pressed{\n"
                                 "    background-color: rgb(0, 172, 0);\n"
                                 "    border-color: rgb(87, 255, 75)\n"
                                 "}\n"
                                 "\n"
                                 "#Cancel{\n"
                                 "    background-color: rgb(242, 90, 90);\n"
                                 "    border-color: rgb(255, 0, 0)\n"
                                 "}\n"
                                 "\n"
                                 "#Cancel::hover{\n"
                                 "    background-color: rgb(237, 50, 50);\n"
                                 "    border-color: rgb(255, 0, 0)\n"
                                 "}\n"
                                 "\n"
                                 "#Cancel::pressed{\n"
                                 "    background-color: rgb(255, 0, 0);\n"
                                 "    border-color: rgb(255, 101, 101)\n"
                                 "}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.Introduction = QtWidgets.QLabel(self.frame)
        self.Introduction.setObjectName("Introduction")
        self.verticalLayout.addWidget(self.Introduction)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.Name = QtWidgets.QFrame(self.frame)
        self.Name.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Name.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Name.setObjectName("Name")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Name)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Name_4 = QtWidgets.QLabel(self.Name)
        self.Name_4.setStyleSheet("QLabel{\n"
                                  "    margin-right: 74px;\n"
                                  "}")
        self.Name_4.setObjectName("Name_4")
        self.horizontalLayout_2.addWidget(self.Name_4)
        self.lineEdit = QtWidgets.QLineEdit(self.Name)
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout.addWidget(self.Name)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.Dose = QtWidgets.QFrame(self.frame)
        self.Dose.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Dose.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Dose.setObjectName("Dose")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Dose)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Label = QtWidgets.QLabel(self.Dose)
        self.Label.setStyleSheet("QLabel{\n"
                                 "    margin-right: 96px\n"
                                 "}")
        self.Label.setObjectName("Label")
        self.horizontalLayout.addWidget(self.Label)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Dose)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.verticalLayout.addWidget(self.Dose)
        spacerItem3 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.Type_of_Animal = QtWidgets.QFrame(self.frame)
        self.Type_of_Animal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Type_of_Animal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Type_of_Animal.setObjectName("Type_of_Animal")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Type_of_Animal)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Label_2 = QtWidgets.QLabel(self.Type_of_Animal)
        self.Label_2.setStyleSheet("QLabel{\n"
                                   "    margin-right: 10px\n"
                                   "}")
        self.Label_2.setObjectName("Label_2")
        self.horizontalLayout_4.addWidget(self.Label_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.Type_of_Animal)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_4.addWidget(self.lineEdit_3)
        self.verticalLayout.addWidget(self.Type_of_Animal)
        spacerItem4 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.Value = QtWidgets.QFrame(self.frame)
        self.Value.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Value.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Value.setObjectName("Value")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.Value)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Label_3 = QtWidgets.QLabel(self.Value)
        self.Label_3.setStyleSheet("QLabel{\n"
                                   "    margin-right: 94px\n"
                                   "}")
        self.Label_3.setObjectName("Label_3")
        self.horizontalLayout_5.addWidget(self.Label_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.Value)
        self.lineEdit_4.setStyleSheet("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_5.addWidget(self.lineEdit_4)
        self.verticalLayout.addWidget(self.Value)
        spacerItem5 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Cancel = QtWidgets.QPushButton(
            self.frame, clicked=lambda: self.back_add_product_window(Add_Antibiotic, Add_Product))
        self.Cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Cancel.setObjectName("Cancel")
        self.horizontalLayout_3.addWidget(self.Cancel)
        spacerItem6 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.Add = QtWidgets.QPushButton(self.frame, clicked=lambda: self.return_main_menu_window(
            Add_Antibiotic, Add_Product, Main_Menu))
        self.Add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Add.setObjectName("Add")
        self.horizontalLayout_3.addWidget(self.Add)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem7 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        Add_Antibiotic.setCentralWidget(self.Background)

        Add_Product.hide()

        self.retranslateUi(Add_Antibiotic)
        QtCore.QMetaObject.connectSlotsByName(Add_Antibiotic)

    def retranslateUi(self, Add_Antibiotic):
        _translate = QtCore.QCoreApplication.translate
        Add_Antibiotic.setWindowTitle(_translate(
            "Add_Antibiotic", "Agregar Antibiótico"))
        self.Introduction.setText(_translate("Add_Antibiotic",
                                             "<html><head/><body><p align=\"center\"><span style=\" "
                                             "font-size:15pt;\">Ingrese los datos del nuevo "
                                             "antibiótico</span></p></body></html>"))
        self.Name_4.setText(_translate("Add_Antibiotic", "Nombre"))
        self.Label.setText(_translate("Add_Antibiotic", "Dosis"))
        self.Label_2.setText(_translate("Add_Antibiotic", "Tipo de Animal"))
        self.Label_3.setText(_translate("Add_Antibiotic", "Costo"))
        self.Cancel.setText(_translate("Add_Antibiotic", "Cancelar"))
        self.Add.setText(_translate("Add_Antibiotic", "Agregar"))

    def create_object(self):
        name = self.lineEdit.text()
        dose = self.lineEdit_2.text()
        animal_type = self.lineEdit_3.text()
        value = self.lineEdit_4.text()
        variables = locals()
        variables.pop("self")
        if validate_items(*variables.values()):
            try:
                variables["value"] = int(variables["value"])
                antibiotic_controller.AntibioticController.create(**variables)
                return True
            except ValueError:
                show_pop_up("Error", "El costo debe ser numerico",
                            QtWidgets.QMessageBox.Warning)
        else:
            show_pop_up("Error", "Debe ingresar todos los valores",
                        QtWidgets.QMessageBox.Warning)

        return False

    def return_main_menu_window(self, Add_Antibiotic, Add_Product, Main_Menu):
        if not self.create_object():
            return
        show_message("Se ha guardado el nuevo producto con exito")
        Main_Menu.show()
        Add_Product.close()
        Add_Antibiotic.close()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Add_Antibiotic = QtWidgets.QMainWindow()
    ui = Ui_Add_Antibiotic()
    ui.setupUi(Add_Antibiotic)
    Add_Antibiotic.show()
    sys.exit(app.exec_())
